export default {
  CLEAR_CONTACT: "CLEAR_CONTACT",
  POPULATE_CONTACT_CARD: "POPULATE_CONTACT_CARD",
  RESET_CONTACT_CARD: "RESET_CONTACT_CARD",
  SAVE_CONTACT: "SAVE_CONTACT",
  SHOW_MODAL: "SHOW_MODAL",
  HIDE_MODAL: "HIDE_MODAL"
};
